name: pdf_viewer_jk
description: A flutter plugin for viewing PDF files in mobile app (Android & iOS).
version: 2.1.5
repository: https://github.com/jawadsahil/pdf_viewer_jk
homepage: https://jawad.pro

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.9.0
  flutter_cache_manager: ^3.3.0
  flutter_spinbox: ^0.11.0
  flutter_svg: ^1.1.6
  http: ^0.13.5
  path_provider: ^2.0.11
  path: ^1.8.2
  pool: ^1.5.1

flutter:
  plugin:
    platforms:
      android:
        package: pro.jawad.pdf_viewer_jk
        pluginClass: PdfViewerJkPlugin
      ios:
        pluginClass: PdfViewerJkPlugin
